-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 11:02:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `expressFood` ;

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expressFood` DEFAULT CHARACTER SET utf8 ;
USE `expressFood` ;

-- -----------------------------------------------------
-- Table `expressFood`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`customer` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `identifier` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`address` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `postal_code` INT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `complement` VARCHAR(100) NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`address_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`address_line` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`address_line` (
  `customer_id` INT NOT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `adress_id`),
  INDEX `adress_id_idx` (`adress_id` ASC),
  CONSTRAINT `addres_line_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `expressFood`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adress_line_adress_id`
    FOREIGN KEY (`adress_id`)
    REFERENCES `expressFood`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`employee` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `identifier` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `type` ENUM('delivery_boy', 'chef', 'administrator') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`delivery_boy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`delivery_boy` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`delivery_boy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('avaliable', 'in_delivery', 'incident', 'refueling') NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `employee_id` INT NOT NULL,
  `stock_dish_one` INT NOT NULL,
  `stock_dish_two` INT NOT NULL,
  `stock_dessert_one` INT NOT NULL,
  `stock_dessert_two` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `employee_id_idx` (`employee_id` ASC),
  CONSTRAINT `delivery_boy_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `expressFood`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`menu` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`dish` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`dish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `picture` VARCHAR(250) NOT NULL,
  `type` ENUM('dish', 'dessert') NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`menu_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`menu_line` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`menu_line` (
  `menu_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`menu_id`, `dish_id`),
  INDEX `dish_id_idx` (`dish_id` ASC),
  CONSTRAINT `menu_line_menu_id`
    FOREIGN KEY (`menu_id`)
    REFERENCES `expressFood`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `menu_line_dish_id`
    FOREIGN KEY (`dish_id`)
    REFERENCES `expressFood`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`order` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `billing_address` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `state` ENUM('validated', 'in_delivery', 'canceled', 'delivered') NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `address_line_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `delivery_boy_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `delivery_boy_id_idx` (`delivery_boy_id` ASC),
  INDEX `address_line_id_idx` (`address_line_id` ASC),
  CONSTRAINT `order_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `expressFood`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_delivery_boy_id`
    FOREIGN KEY (`delivery_boy_id`)
    REFERENCES `expressFood`.`delivery_boy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_address_line_id`
    FOREIGN KEY (`address_line_id`)
    REFERENCES `expressFood`.`address_line` (`adress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`order_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`order_line` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`order_line` (
  `order_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `dish_id`),
  INDEX `dish_id_idx` (`dish_id` ASC),
  CONSTRAINT `order_line_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `expressFood`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_line_dish_id`
    FOREIGN KEY (`dish_id`)
    REFERENCES `expressFood`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
